name: Dev - Destroy
on: [workflow_dispatch]
jobs:
  TerraformDestroy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2022
          - windows-latest
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-latest
          - macos-11
          - macos-12
          - macos-12-xl
          - macos-13
          - macos-13-xl
          - macos-latest
          - macos-latest-xl
    env:
      vault_token: ${{ secrets.vault_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault-int.mydevops.shop:8200/
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            roboshop-infra/data/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            roboshop-infra/data/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;
            roboshop-infra/data/azure-sp ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID ;
      - name: Terraform Destroy
        run: |
          export ARM_CLIENT_ID="${{ env.ARM_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ env.ARM_CLIENT_SECRET }}"
          export ARM_TENANT_ID="${{ env.ARM_TENANT_ID }}"
          export ARM_SUBSCRIPTION_ID="${{ env.ARM_SUBSCRIPTION_ID }}"
          make dev-destroy token=${vault_token}

